title: diesdas
description: diesdas
url: ""

# Build settings
plugins:
  - jekyll-postcss
sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]

# Variables
start_date: 2022-06-20
end_date: 2022-07-31

# Production variables
cuttly_count: "https://cutt.ly/fliwo24"

